server {
    listen 80;

    resolver 127.0.0.11 valid=30s;

    location /financeiro/ {
        set $upstream_financeiro web-financeiro:9501;
        proxy_pass http://$upstream_financeiro/;
    }

    location /mkt/ {
        set $upstream_mkt web-mkt:3000;
        proxy_pass http://$upstream_mkt/;
    }

    location /academico/ {
        set $upstream_academico web-academico:8080;
        proxy_pass http://$upstream_academico/;
    }
}
