spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

server.port=0

#Ativando o mecanismo para configurações de retry automatico
spring.rabbitmq.listener.simple.retry.enabled=true
#Quantidade de tentativas de consumo antes de enviar para a DLQ
spring.rabbitmq.listener.simple.retry.max-attempts=3
#Exponential backoff
spring.rabbitmq.listener.simple.retry.initial-interval=5000
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=15000